/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sisesp;

/**
 *
 * @author rodolfosmac
 */

/*  RuleApplet class

   Constructing Intelligent Agents with Java
   (C) Joseph P.Bigus and Jennifer Bigus 1997

*/

import java.applet.*;
import java.awt.CheckboxGroup;

public class RuleApplet extends Applet {

     // Note this code is generated by Visual Cafe&#146;
     //{{DECLARE_CONTROLS
     java.awt.Button button1;
     java.awt.Button button2;
     java.awt.Button button3;
     java.awt.TextArea textArea1;
     java.awt.TextArea textArea2;
     java.awt.Label label2;
     java.awt.Label label1;
     java.awt.Choice choice1;
     java.awt.Checkbox radioButton1;
     CheckboxGroup Group1;
     java.awt.Choice choice3;
     java.awt.Label label5;
     java.awt.Choice choice2;
     java.awt.TextArea textArea3;
     java.awt.Label label4;
     java.awt.Checkbox radioButton2;
     java.awt.TextField textField1;
     java.awt.Label label3;


//     private Frame frame;
//     //static RuleVarDialog dlg ;
//     static BooleanRuleBase bugs ;
//     static BooleanRuleBase plants ;
//     static BooleanRuleBase vehicles ;
//     static BooleanRuleBase currentRuleBase ;
//    
//    
//    
//    // user selected a rule base
//    public void choice1_Clicked() {
//       String rbName = choice1.getSelectedItem() ;
//       if (rbName.equals("Vehicles")) currentRuleBase = vehicles ;
//       if (rbName.equals("Bugs")) currentRuleBase = bugs ;
//       if (rbName.equals("Plants")) currentRuleBase = plants ;
//
//       currentRuleBase.reset() ;  // reset the rule base
//       Enumeration vars = currentRuleBase.variableList.elements() ;
//       while (vars.hasMoreElements()) {
//         choice2.addItem(((RuleVariable)vars.nextElement()).name) ;
//       }
//       //currentRuleBase.displayVariables(textArea3) ;
//
//     }
//
//    // user selected a variable
//    public void choice2_Clicked(Event event) {
//       String varName = choice2.getSelectedItem() ;
//       choice3.removeAll() ;
//
//       RuleVariable rvar =
//       (RuleVariable)currentRuleBase.variableList.get(varName);
//       Enumeration labels = rvar.labels.elements();
//       while (labels.hasMoreElements()) {
//          choice3.addItem(((String)labels.nextElement())) ;
//       }
//     }
//    // user selected a value for a variable
//    public void choice3_Clicked(Event event) {
//       String varName = choice2.getSelectedItem() ;
//       String varValue = choice3.getSelectedItem() ;
//
//       RuleVariable rvar =
//          (RuleVariable)currentRuleBase.variableList.get(varName);
//       rvar.setValue(varValue) ;
//       textArea3.appendText(&#147;\n&#148;&#43; rvar.name &#43; &#147; set to &#148;&#43; varValue) ;
//     }
//
//    // user pressed Find button -- do an infernece cycle
//     public void button1_Clicked(Event event) {
//       String goal = textField1.getText() ;
//
//       textArea2.appendText(&#147;\n --- Starting Inferencing Cycle --- \n&#148;);
//       currentRuleBase.displayVariables(textArea2) ;
//       if (radioButton1.getState() == true)
//           currentRuleBase.forwardChain();
//       if (radioButton2.getState() == true)
//           currentRuleBase.backwardChain(goal);
//       currentRuleBase.displayVariables(textArea2) ;
//       textArea2.appendText(&#147;\n --- Ending Inferencing Cycle --- \n&#148;);
//    }
//
//    // user pressed Demo button -- do inference with pre-set values
//    public void button2_Clicked(Event event) {
//       String rbName = choice1.getSelectedItem() ;
//       if (rbName.equals(&#147;Vehicles&#148;)) {
//         if (radioButton1.getState() == true)
//             demoVehiclesFC(vehicles);
//         if (radioButton2.getState() == true)
//             demoVehiclesBC(vehicles);
//      } else if (rbName.equals(&#147;Bugs&#148;)) {
//         if (radioButton1.getState() == true) demoBugsFC(bugs);
//         if (radioButton2.getState() == true) demoBugsBC(bugs);
//      } else {
//         if (radioButton1.getState() == true) demoPlantsFC(plants);
//         if (radioButton2.getState() == true) demoPlantsBC(plants);
//      }
//     }
//
//    // User press the Reset button
//    void button3_Clicked(Event event) {
//
//           //{{CONNECTION
//           // Clear the text for TextArea
//           textArea1.setText(&#147;&#148;);
//           textArea2.setText(&#147;&#148;);
//           textArea3.setText(&#147;&#148;);
//           //}}
//
//        currentRuleBase.reset() ;
//        currentRuleBase.displayRules(textArea1);
//        currentRuleBase.displayVariables(textArea3) ;
//     }
//
//     public void init() {
//        super.init();
//
//           // Note, this code is generated by Visual Cafe&#146;
//           //{{INIT_CONTROLS
//           setLayout(null);
//           addNotify();
//           resize(624,527);
//           button1 = new java.awt.Button(&#147;Find Goal&#148;);
//           button1.reshape(36,468,108,30);
//           add(button1);
//           button2 = new java.awt.Button(&#147;Run Demo&#148;);
//           button2.reshape(228,468,108,30);
//           add(button2);
//           button3 = new java.awt.Button(&#147;Reset&#148;);
//           button3.reshape(444,468,108,30);
//           add(button3);
//           textArea1 = new java.awt.TextArea();
//           textArea1.reshape(12,48,312,144);
//           add(textArea1);
//           textArea2 = new java.awt.TextArea();
//           textArea2.reshape(12,216,600,168);
//           add(textArea2);
//           label2 = new java.awt.Label(&#147;Trace Log&#148;);
//           label2.reshape(24,192,168,24);
//           add(label2);
//           label1 = new java.awt.Label(&#147;Rule Base&#148;);
//           label1.reshape(24,12,96,24);
//           add(label1);
//           choice1 = new java.awt.Choice();
//           add(choice1);
//           choice1.reshape(132,12,192,24);
//           Group1 = new CheckboxGroup();
//           radioButton1 = new java.awt.Checkbox(&#147;Forward Chain&#148;,
//           Group1, false);
//           radioButton1.reshape(36,396,156,21);
//           add(radioButton1);
//           choice3 = new java.awt.Choice();
//           add(choice3);
//           choice3.reshape(480,36,135,24);
//           label5 = new java.awt.Label(&#147;Value&#148;);
//           label5.reshape(480,12,95,24);
//           add(label5);
//           choice2 = new java.awt.Choice();
//           add(choice2);
//           choice2.reshape(336,36,137,24);
//           textArea3 = new java.awt.TextArea();
//           textArea3.reshape(336,72,276,122);
//           add(textArea3);
//           label4 = new java.awt.Label(&#147;Variable&#148;);
//           label4.reshape(336,12,109,24);
//           add(label4);
//           radioButton2 = new java.awt.Checkbox(&#147;Backward Chain&#148;,
//                                                Group1, false);
//           radioButton2.reshape(36,420,156,24);
//           add(radioButton2);
//           textField1 = new java.awt.TextField();
//           textField1.reshape(324,420,142,27);
//           add(textField1);
//           label3 = new java.awt.Label(&#147;Goal&#148;);
//           label3.reshape(324,384,80,30);
//           add(label3);
//           //}}
//
//           // initialize the rule applet
//           frame = new Frame(&#147;Ask User&#148;) ;
//           frame.resize(50,50) ;
//           frame.setLocation(100,100) ;
//           choice1.addItem(&#147;Vehicles&#148;) ;
//           choice1.addItem(&#147;Bugs&#148;) ;
//           choice1.addItem(&#147;Plants&#148;) ;
//
//           vehicles = new RuleBase(&#147;Vehicles Rule Base&#148;) ;
//           vehicles.setDisplay(textArea2) ;
//           initVehiclesRuleBase(vehicles) ;
//           currentRuleBase = vehicles ;
//
//           bugs = new RuleBase(&#147;Bugs Rule Base&#148;) ;
//           bugs.setDisplay(textArea2) ;
//           initBugsRuleBase(bugs) ;
//
//           plants = new RuleBase(&#147;Plants Rule Base&#148;) ;
//           plants.setDisplay(textArea2) ;
//           initPlantsRuleBase(plants) ;
//
//        // initialize textAreas and list controls
//        currentRuleBase.displayRules(textArea1) ;
//        currentRuleBase.displayVariables(textArea3) ;
//        radioButton1.setState(true) ;
//        choice1_Clicked() ; // fill variable list
//     }
//
//      // Note: this is Java 1.0.2 event model
//      public boolean handleEvent(Event event) {
//           if (event.target == button1 &amp&amp
//               event.id == Event.ACTION_EVENT) {
//                button1_Clicked(event);
//                return true;
//           }if (event.target == button2 &amp&amp
//                event.id == Event.ACTION_EVENT) {
//                button2_Clicked(event);
//                return true;
//           }if (event.target == button3 &amp&amp
//                event.id == Event.ACTION_EVENT) {
//                button3_Clicked(event);
//                return true;
//           }
//           if (event.target == dlg &amp&amp
//                event.id == Event.ACTION_EVENT) {
//                return dlg.handleEvent(event);
//           }
//          if (event.target == choice1 &amp&amp
//               event.id == Event.ACTION_EVENT) {
//                choice1_Clicked();
//                return true;
//          }
//          if (event.target == choice2 &amp&amp
//             event.id == Event.ACTION_EVENT) {
//                choice2_Clicked(event);
//                return true;
//          }
//            if (event.target == choice3 &amp&amp
//                 event.id == Event.ACTION_EVENT) {
//                choice3_Clicked(event);
//                return true;
//          }
//           return super.handleEvent(event);
//     }
//// Rule base definitions

}
